### ISSUE TITLE
Could i pass signer seeds to initialize api to let my contract to create pool with tokens hold by contract itself.

### ISSUE THREAD

**Issue by benhaben** [raydium-io/raydium-cp-swap#19]
![image](https://github.com/user-attachments/assets/ad9612ba-3af6-44e4-a6a9-29b8a74758c8)

**Comment by benhaben** [comment]
Could i pass signer seeds to initialize api to let my contract to create pool with tokens hold by contract itself.
It seems we only can intialzlize token by eoa address.

**Comment by liupan163** [comment]
@benhaben Hello, sir. I have the same requirement. Did you successfully achieve that using a contract to create a pool?

**Comment by RainRaydium** [comment]
Yes.
I thank you can specify your program's `authority` as the `creator`, and ensure that your program `authority` has enough sols to pay the rent, and the program `authority` is not allocated any space.
Because when the solana system program creates an account to transfer rent, the lamports from account is not allowed to have any data.
refer:[https://github.com/solana-labs/solana/blob/master/programs/system/src/system_processor.rs#L192](url)
